// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.1
// source: api/proto/infraflow/v1/agent.proto

package infrav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentProvider_ListArtifacts_FullMethodName    = "/infraflow.v1.AgentProvider/ListArtifacts"
	AgentProvider_DownloadArtifact_FullMethodName = "/infraflow.v1.AgentProvider/DownloadArtifact"
	AgentProvider_ReportState_FullMethodName      = "/infraflow.v1.AgentProvider/ReportState"
)

// AgentProviderClient is the client API for AgentProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentProviderClient interface {
	ListArtifacts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ArtifactCatalog, error)
	DownloadArtifact(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ArtifactChunk], error)
	ReportState(ctx context.Context, in *AgentStateReport, opts ...grpc.CallOption) (*ReportAck, error)
}

type agentProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentProviderClient(cc grpc.ClientConnInterface) AgentProviderClient {
	return &agentProviderClient{cc}
}

func (c *agentProviderClient) ListArtifacts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ArtifactCatalog, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArtifactCatalog)
	err := c.cc.Invoke(ctx, AgentProvider_ListArtifacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentProviderClient) DownloadArtifact(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ArtifactChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentProvider_ServiceDesc.Streams[0], AgentProvider_DownloadArtifact_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadRequest, ArtifactChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentProvider_DownloadArtifactClient = grpc.ServerStreamingClient[ArtifactChunk]

func (c *agentProviderClient) ReportState(ctx context.Context, in *AgentStateReport, opts ...grpc.CallOption) (*ReportAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportAck)
	err := c.cc.Invoke(ctx, AgentProvider_ReportState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentProviderServer is the server API for AgentProvider service.
// All implementations must embed UnimplementedAgentProviderServer
// for forward compatibility.
type AgentProviderServer interface {
	ListArtifacts(context.Context, *Empty) (*ArtifactCatalog, error)
	DownloadArtifact(*DownloadRequest, grpc.ServerStreamingServer[ArtifactChunk]) error
	ReportState(context.Context, *AgentStateReport) (*ReportAck, error)
	mustEmbedUnimplementedAgentProviderServer()
}

// UnimplementedAgentProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentProviderServer struct{}

func (UnimplementedAgentProviderServer) ListArtifacts(context.Context, *Empty) (*ArtifactCatalog, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListArtifacts not implemented")
}
func (UnimplementedAgentProviderServer) DownloadArtifact(*DownloadRequest, grpc.ServerStreamingServer[ArtifactChunk]) error {
	return status.Errorf(codes.Unimplemented, "method DownloadArtifact not implemented")
}
func (UnimplementedAgentProviderServer) ReportState(context.Context, *AgentStateReport) (*ReportAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportState not implemented")
}
func (UnimplementedAgentProviderServer) mustEmbedUnimplementedAgentProviderServer() {}
func (UnimplementedAgentProviderServer) testEmbeddedByValue()                       {}

// UnsafeAgentProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentProviderServer will
// result in compilation errors.
type UnsafeAgentProviderServer interface {
	mustEmbedUnimplementedAgentProviderServer()
}

func RegisterAgentProviderServer(s grpc.ServiceRegistrar, srv AgentProviderServer) {
	// If the following call pancis, it indicates UnimplementedAgentProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentProvider_ServiceDesc, srv)
}

func _AgentProvider_ListArtifacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentProviderServer).ListArtifacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentProvider_ListArtifacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentProviderServer).ListArtifacts(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentProvider_DownloadArtifact_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentProviderServer).DownloadArtifact(m, &grpc.GenericServerStream[DownloadRequest, ArtifactChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentProvider_DownloadArtifactServer = grpc.ServerStreamingServer[ArtifactChunk]

func _AgentProvider_ReportState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentStateReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentProviderServer).ReportState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentProvider_ReportState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentProviderServer).ReportState(ctx, req.(*AgentStateReport))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentProvider_ServiceDesc is the grpc.ServiceDesc for AgentProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "infraflow.v1.AgentProvider",
	HandlerType: (*AgentProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListArtifacts",
			Handler:    _AgentProvider_ListArtifacts_Handler,
		},
		{
			MethodName: "ReportState",
			Handler:    _AgentProvider_ReportState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadArtifact",
			Handler:       _AgentProvider_DownloadArtifact_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/infraflow/v1/agent.proto",
}
